"""initial schema

Revision ID: 453f1135957b
Revises: 
Create Date: 2026-05-29 12:12:43.769322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '453f1135957b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_pipeline_runs_status'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_property_id', 'pipeline_runs', ['property_id'], unique=False)
    op.create_index('ix_pipeline_runs_running', 'pipeline_runs', ['id'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('room_type', sa.String(length=20), nullable=True),
    sa.Column('actionable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pass1_confidence', sa.Float(), nullable=True),
    sa.Column('condition_score', sa.SmallInteger(), nullable=True),
    sa.Column('modernity_score', sa.SmallInteger(), nullable=True),
    sa.Column('material_score', sa.SmallInteger(), nullable=True),
    sa.Column('functionality_score', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("room_type IN ('bedroom', 'bathroom', 'kitchen', 'living_room', 'dining_room', 'hallway', 'garage', 'exterior', 'unknown')", name='ck_images_room_type'),
    sa.CheckConstraint('condition_score BETWEEN 1 AND 5', name='ck_images_condition'),
    sa.CheckConstraint('functionality_score BETWEEN 1 AND 5', name='ck_images_functionality'),
    sa.CheckConstraint('material_score BETWEEN 1 AND 5', name='ck_images_material'),
    sa.CheckConstraint('modernity_score BETWEEN 1 AND 5', name='ck_images_modernity'),
    sa.CheckConstraint('pass1_confidence >= 0 AND pass1_confidence <= 1', name='ck_images_pass1_confidence'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'filename', name='uq_images_property_filename')
    )
    op.create_index('ix_images_property_id', 'images', ['property_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('condition_score', sa.SmallInteger(), nullable=True),
    sa.Column('modernity_score', sa.SmallInteger(), nullable=True),
    sa.Column('material_score', sa.SmallInteger(), nullable=True),
    sa.Column('functionality_score', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("room_type IN ('bedroom', 'bathroom', 'kitchen', 'living_room', 'dining_room', 'hallway', 'garage', 'exterior', 'unknown')", name='ck_rooms_room_type'),
    sa.CheckConstraint('condition_score BETWEEN 1 AND 5', name='ck_rooms_condition'),
    sa.CheckConstraint('functionality_score BETWEEN 1 AND 5', name='ck_rooms_functionality'),
    sa.CheckConstraint('material_score BETWEEN 1 AND 5', name='ck_rooms_material'),
    sa.CheckConstraint('modernity_score BETWEEN 1 AND 5', name='ck_rooms_modernity'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'room_type', name='uq_rooms_property_room_type')
    )
    op.create_index('ix_rooms_property_id', 'rooms', ['property_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('feature_id', sa.String(length=50), nullable=True),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('classification', sa.String(length=10), nullable=True),
    sa.Column('score_type', sa.String(length=20), nullable=True),
    sa.Column('score_value', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IS NULL OR classification IN ('correct', 'fp', 'fn')", name='ck_feedback_classification'),
    sa.CheckConstraint("feedback_type IN ('classification', 'verdict', 'score')", name='ck_feedback_type'),
    sa.CheckConstraint("score_type IS NULL OR score_type IN ('condition', 'modernity', 'material', 'functionality')", name='ck_feedback_score_type'),
    sa.CheckConstraint("verdict IS NULL OR verdict IN ('agree', 'disagree')", name='ck_feedback_verdict'),
    sa.CheckConstraint('score_value IS NULL OR score_value BETWEEN 1 AND 5', name='ck_feedback_score_value'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_latest_class', 'feedback', ['image_id', 'feedback_type', 'created_at'], unique=False)
    op.create_index('ix_feedback_property_id', 'feedback', ['property_id'], unique=False)
    op.create_table('image_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.CheckConstraint("feature_id IN ('water_damage', 'mold', 'broken_fixture', 'stained_carpet', 'cracked_tile')", name='ck_imgfeat_feature_id'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name='ck_imgfeat_severity'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_imgfeat_confidence'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_features_image_id', 'image_features', ['image_id'], unique=False)
    op.create_table('room_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.CheckConstraint("feature_id IN ('water_damage', 'mold', 'broken_fixture', 'stained_carpet', 'cracked_tile')", name='ck_roomfeat_feature_id'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name='ck_roomfeat_severity'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_roomfeat_confidence'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_features_room_id', 'room_features', ['room_id'], unique=False)
    # ### end Alembic commands ###

    # --- DBMS feature: auto-update properties.updated_at on every UPDATE ---
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_properties_updated_at
        BEFORE UPDATE ON properties
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
    """)

    # --- DBMS feature: stats view for the summary dashboard ---
    op.execute("""
        CREATE VIEW v_property_stats AS
        SELECT
            p.id AS property_id,
            p.property_id AS external_id,
            COUNT(DISTINCT i.id) AS total_images,
            COUNT(DISTINCT i.id) FILTER (WHERE i.room_type IN ('kitchen','bathroom')) AS kb_images,
            COUNT(DISTINCT i.id) FILTER (WHERE i.actionable) AS actionable_images,
            COUNT(f.id) AS total_features,
            COUNT(f.id) FILTER (WHERE f.severity = 'high') AS high_severity_count,
            AVG(i.pass1_confidence) AS avg_pass1_confidence
        FROM properties p
        LEFT JOIN images i ON i.property_id = p.id
        LEFT JOIN image_features f ON f.image_id = i.id
        GROUP BY p.id, p.property_id;
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_property_stats;")
    op.execute("DROP TRIGGER IF EXISTS trg_properties_updated_at ON properties;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_features_room_id', table_name='room_features')
    op.drop_table('room_features')
    op.drop_index('ix_image_features_image_id', table_name='image_features')
    op.drop_table('image_features')
    op.drop_index('ix_feedback_property_id', table_name='feedback')
    op.drop_index('ix_feedback_latest_class', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_rooms_property_id', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_images_property_id', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_pipeline_runs_running', table_name='pipeline_runs', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('ix_pipeline_runs_property_id', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('properties')
    # ### end Alembic commands ###
